# Site settings
title: How Far Are We From AGI？
description: ICLR AGI Workshop
domain: 
url: 
baseurl: ''
year: 2024
all_years:
  - 2024


author:
  name: 'Jiaxuan You & Tao Feng'

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
include: ['_posts']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
